version: "3"
services:
  app:
    image: pritamscrobits/app:1.0
    ports:
      - 8080:8080
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
